# Generated by Django 2.0.7 on 2018-08-11 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('note', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fn', models.CharField(max_length=255, unique=True, verbose_name='Full Name')),
                ('x_phonetic_first_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Phonetic First Name')),
                ('x_phonetic_last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Phonetic Last Name')),
                ('nickname', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nickname')),
                ('x_pronouns', models.CharField(blank=True, max_length=255, null=True, verbose_name='Pronouns')),
                ('org', models.CharField(blank=True, max_length=255, null=True, verbose_name='Organization')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Job Title')),
                ('tel_cell', models.CharField(blank=True, max_length=255, null=True, verbose_name='Mobile/Cell/Handy')),
                ('tel_work', models.CharField(blank=True, max_length=255, null=True, verbose_name='Work Phone')),
                ('tel_home', models.CharField(blank=True, max_length=255, null=True, verbose_name='Home Phone')),
                ('tel_other', models.CharField(blank=True, max_length=255, null=True, verbose_name='Telephone Other')),
                ('label_work', models.CharField(blank=True, max_length=255, null=True, verbose_name='Work Address')),
                ('label_home', models.CharField(blank=True, max_length=255, null=True, verbose_name='Home Address')),
                ('label_other', models.CharField(blank=True, max_length=255, null=True, verbose_name='Address Other')),
                ('email_personal', models.CharField(blank=True, max_length=255, null=True, verbose_name='Personal Email')),
                ('email_work', models.CharField(blank=True, max_length=255, null=True, verbose_name='Work Email')),
                ('email_other', models.CharField(blank=True, max_length=255, null=True, verbose_name='Email Other')),
                ('url_1', models.CharField(blank=True, max_length=255, null=True, verbose_name='Url')),
                ('url_2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Url')),
                ('url_3', models.CharField(blank=True, max_length=255, null=True, verbose_name='Url')),
                ('url_4', models.CharField(blank=True, max_length=255, null=True, verbose_name='Url')),
                ('bday', models.DateField(blank=True, help_text='A date in YYYY-MM-DD format', null=True, verbose_name='Birthday')),
                ('x_anniversary', models.DateField(blank=True, help_text='A date in YYYY-MM-DD format', null=True, verbose_name='Anniversary')),
                ('geo', models.CharField(blank=True, help_text='A set of coordinates, such as 39.95;-75.1667', max_length=255, null=True, verbose_name='Geolocation')),
                ('tz', models.CharField(blank=True, help_text='A timezone, such as -0500', max_length=255, null=True, verbose_name='Timezone')),
                ('impp', models.CharField(blank=True, max_length=255, null=True, verbose_name='IMPP')),
                ('birthplace', models.CharField(blank=True, max_length=255, null=True, verbose_name='Birthplace')),
                ('why', models.TextField(blank=True, null=True, verbose_name='Why is this person in the address book?')),
                ('categories', models.CharField(blank=True, help_text='A comma separated list of categories', max_length=255, null=True, verbose_name='Categories')),
                ('rev', models.DateTimeField(auto_now=True, verbose_name='Revised')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('next_contact_date', models.DateField(blank=True, help_text='A date in YYYY-MM-DD format', null=True, verbose_name='Next Contact Date')),
                ('frequency', models.PositiveSmallIntegerField(choices=[(0, 'Never'), (1, 'Yearly'), (2, 'Twice per annum'), (3, 'Quarterly'), (4, 'Monthly'), (5, 'Biweekly'), (6, 'Weekly'), (7, 'Daily')], default=2, verbose_name='Desired Frequency of Contact')),
            ],
        ),
        migrations.AddField(
            model_name='note',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note', to='whenandwho.Record'),
        ),
    ]
